project:
  type: book
  output-dir: docs
book:
  title: "An Insider's Guide to Mastering Mergers, Acquisitions & Power Plant Development"
  subtitle: "Best Practices for Risk Analysis and Risk Mitigation to Ensure Transaction Closing"
  author: "Kimberlee Centera"
  date: today
  chapters:
    - index.qmd
    - foreword.qmd
    - dedication.qmd
    - about-author.qmd
    - legal-disclaimer.qmd
    - contents.qmd
    - introduction.qmd
    - chapters01-fundamentals.qmd
    - chapters02-land-control.qmd
    - chapters03-ownership.qmd
    - chapters04-mineral-rights.qmd
    - chapters05-due-diligence.qmd
    - chapters06-environmental.qmd
    - chapters07-hidden-ownership.qmd
    - chapters08-collaboration.qmd
    - chapters09-valuation.qmd
    - chapters10-inheriting.qmd
    - chapters11-project-finance.qmd
    - chapters12-ai-risk.qmd
    - chapters13-nature-based.qmd
    - acknowledgments.qmd
    - appendix.qmd
format:
  html:
    theme: [cosmo, _custom.scss]
    toc: true
    toc-depth: 3
    number-sections: false
    include-before-body: _condensed-banner.html
execute:
  freeze: auto
