# Contents

**INTRODUCTION:** Why Mergers and Acquisitions are Shaping the Renewable Energy Future

1. Navigating M&A Best Practices in Utility-Scale Renewable Energy Development
2. Verifying Land Control – The Foundation of Acquisition
3. Ensuring Correct Ownership – Getting the Signatures Right
4. Unseen Challenges - Navigating Mineral Rights
5. Racing the Clock – Due Diligence Strategies for Tight Timelines
6. Environmental and Site Considerations in Project Acquisitions
7. Hidden Layers - Addressing Complex Ownership Structures in Project Acquisitions
8. Enhancing Collaboration Between M&A and Development Teams
9. Accurately Assessing Worth and Timing in Renewable Energy M&A
10. Inheriting a Project - Navigating the Challenges and Leveraging Opportunities
11. The Fundamentals Project Finance for Electricity and Renewable Energy
12. AI the New Frontier in Risk Modeling & Scenario Analysis
13. Mitigating Renewable Infrastructure Risk with Nature-Based Solutions

Acknowledgements – to be completed

Appendix – industry resources for further information to be added
